2018-05-05 21:52:33,528 ERROR: Exception on /edit_profile [POST] [in /Users/jiahuiwu/Desktop/microblog/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/jiahuiwu/Desktop/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/jiahuiwu/Desktop/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/jiahuiwu/Desktop/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/jiahuiwu/Desktop/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/jiahuiwu/Desktop/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/jiahuiwu/Desktop/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jiahuiwu/Desktop/microblog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/jiahuiwu/Desktop/microblog/app/routes.py", line 175, in edit_profile
    filename = images.save(request.files['image'])
  File "/Users/jiahuiwu/Desktop/microblog/venv/lib/python3.6/site-packages/flask_uploads.py", line 422, in save
    os.makedirs(target_folder)
  File "/Users/jiahuiwu/anaconda/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/Users/jiahuiwu/anaconda/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/Users/jiahuiwu/anaconda/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/app'
2018-05-05 22:49:36,103 INFO: Microblog startup [in /Users/jiahuiwu/Desktop/microblog1/app/__init__.py:57]
2018-05-05 22:50:21,103 ERROR: Exception on /edit_profile [POST] [in /Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/jiahuiwu/Desktop/microblog1/app/routes.py", line 175, in edit_profile
    filename = images.save(request.files['image'])
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask_uploads.py", line 422, in save
    os.makedirs(target_folder)
  File "/Users/jiahuiwu/anaconda/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/Users/jiahuiwu/anaconda/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/Users/jiahuiwu/anaconda/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/app'
2018-05-05 22:53:15,662 INFO: Microblog startup [in /Users/jiahuiwu/Desktop/microblog1/app/__init__.py:57]
2018-05-05 22:53:22,829 ERROR: Exception on /edit_profile [POST] [in /Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/jiahuiwu/Desktop/microblog1/app/routes.py", line 175, in edit_profile
    filename = images.save(request.files['image'])
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask_uploads.py", line 422, in save
    os.makedirs(target_folder)
  File "/Users/jiahuiwu/anaconda/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/Users/jiahuiwu/anaconda/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/Users/jiahuiwu/anaconda/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/app'
2018-05-05 22:58:48,889 INFO: Microblog startup [in /Users/jiahuiwu/Desktop/microblog1/app/__init__.py:57]
2018-05-05 22:58:55,282 ERROR: Exception on /edit_profile [POST] [in /Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/jiahuiwu/Desktop/microblog1/app/routes.py", line 175, in edit_profile
    filename = images.save(request.files['image'])
  File "/Users/jiahuiwu/anaconda/lib/python3.6/site-packages/flask_uploads.py", line 422, in save
    os.makedirs(target_folder)
  File "/Users/jiahuiwu/anaconda/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/Users/jiahuiwu/anaconda/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/Users/jiahuiwu/anaconda/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/app'
